project:
  type: website
  output-dir: docs

website:
  title: "Peter T. Tanksley"
  navbar:
    right:  
      # - text: Home
      #   href: index.qmd
      - text: Autobiographical BS
        href: about.qmd
      - text: CV  
        href: cv.qmd  
      - posts.qmd  
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

